name: 'Merge'
description: 'Merge images'
runs:
  using: "composite"
  steps:
    - name: Download digests
      uses: actions/download-artifact@v3
      with:
        name: digests
        path: /tmp/teslamate
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3