name: Ensure Linting

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check_linting:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b #v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix binary cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b #v8

      - name: Run treefmt in CI mode
        run: nix develop . --impure --command treefmt --ci # In a standard Nix flake project, the --impure flag is not needed. However, using devenv in your flake requires the --impure flag., see https://devenv.sh/guides/using-with-flake-parts/#the-flakenix-file
        # or use: https://github.com/cachix/git-hooks.nix?tab=readme-ov-file
