name: Spell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check_paths:
    uses: ./.github/workflows/check_paths.yml

  spell_check:
    name: Spell check
    needs: check_paths
    if: needs.check_paths.outputs.githubfolder == 'false' || github.event_name == 'schedule'
    runs-on: ubuntu-20.04

    steps:
      - name: Spell check
        uses: crate-ci/typos@c16dc8f5b4a7ad6211464ecf136c69c851e8e83c # v1.22.9
