name: Mark and close stale issues and pull requests

on:
  schedule:
    - cron: '21 1 * * 0'  # Run every Sunday at 1:21 AM

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Stale issue cleanup'
          stale-pr-message: 'Stale pull request cleanup'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 365
